New alert to check Thanos Store blocks not being loaded
rhobs/configuration pull request #111
Opened 2022-01-10 17:06 UTC by spaparaju

This PR adds a new RHOBS alert on Thanos Store blocks not being loaded.

2022-01-10 17:14 UTC, ianbillett commented
I'm probably missing something here - but I don't understand how this alert satisfies the acceptance criteria of the [ticket](https://issues.redhat.com/browse/MON-1847)? 
> We get an alert if we detect that RHOBS contains less data retained than expected.

2022-01-10 17:30 UTC, spaparaju commented
After a data loss incident, initial goal of this [issue](https://issues.redhat.com/browse/MON-1847) was to check for resolutions. After couple of discussions, it was concluded that alerting for missing data is more practical and added a new metric `thanos_bucket_store_blocks_last_loaded_timestamp_seconds`. This PR adds a new alert on this new metric to alert if no block has been uploaded for a duration of 6 hours. 

Will update the [issue](https://issues.redhat.com/browse/MON-1847) with the above context.

2022-01-11 09:52 UTC, matej-g commented on docs/sop/observatorium.md
> +During the last 6 hours, not even a single Thanos Store block has been loaded. This can indicate possible data loss.
```suggestion
During the last 6 hours, not even a single Thanos Store block has been loaded.
```

2022-01-11 09:52 UTC, matej-g commented on docs/sop/observatorium.md
> +
I'm missing steps on what to do if this is misconfigured - do we need to update it in the AppSRE Interface? Any other aspects we should be looking out for when changing this config?

2022-01-11 09:52 UTC, matej-g commented on observability/prometheusrules.jsonnet
> +                summary: 'Observatorium Thanos Ruler has not loaded even a sigle block. This should not have happened, indicates data loss. Check out the configuration.',
Maybe we could add information on how long
```suggestion
                summary: 'Observatorium Thanos Ruler has not loaded a single block in the last 6 hours.',
```

2022-01-11 09:52 UTC, matej-g commented on observability/prometheusrules.jsonnet
> +                severity: 'critical',
Should this be `critical`? Should this get someone 'out of the bed' so to speak? :smile:

2022-01-11 12:09 UTC, ianbillett requested changes
Sorry @spaparaju but I really don't think that this alert is telling us anything valuable about data loss in our RHOBS infrastructure.

The metric `thanos_bucket_store_blocks_last_loaded_timestamp_seconds` tells us the most recent time that `Store` loaded a block from object storage.

If this exceeds 6 hours, this does not indicate data loss (i.e. deleting blocks from object storage), this would indicate that new blocks are not being uploaded to object storage.

Blocks are uploaded via `Receive` or `Compactor`, for which we already have fairly comprehensive set of alerts - which leads me to think that we already have the 'alerting on data not being uploaded' path covered.

2022-01-12 02:58 UTC, spaparaju commented
@ianbillett the metric  `thanos_bucket_store_blocks_last_loaded_timestamp_seconds` is updated every time a new block is found (repeated by  `--sync-block-duration` flag of the Store) to be synced between local (disk) and remote view. 

Last time when we ran into data loss issue, based on Compactor flags we chose resulted in the data loss i.e. Compactor did not create any new bigger blocks as expected.  This alert tries to address this specific path which might result in the data loss.

Question: From `Receive` / `Compactor`,  can you please point me to any existing alerts that we can leverage for the above scenario which has resulted in data loss ?

2022-01-12 10:14 UTC, matej-g commented
I think we might just all understand the 'data loss' differently here, if I'm reading the conversations correctly. While this alert does not mean we lost existing data, it is indicating that even though we should be continuously seeing new data being loaded, there was nothing loaded in last 6 hours - this can indicate that there is something wrong with data ingestion and that we are 'losing' this data, since we're not seeing them being loaded and they perhaps are getting 'lost' somewhere on the way to us (e.g. due to misconfiguration). 

Does that make sense @spaparaju @ianbillett? 

As for similar alerts, we are alerting on compactor not uploading in the last 24 hours and there is also `ThanosReceiveNoUpload`, but I guess we don't have similar alerting from the store side.

2022-01-12 11:09 UTC, ianbillett commented on docs/sop/observatorium.md
> +        - --retention.resolution-1h
This alert would not have fired in the compactor incident as `Receive` was still uploading blocks to object storage that `Store` was syncing and serving.

2022-01-12 23:11 UTC, spaparaju commented on docs/sop/observatorium.md
> +
Currently setting all the resolutions (raw, 5m, 1h) to the same duration makes Compactor works as expected. I dont think this fact is not documented at  https://thanos.io/tip/components/compact.md/.  There are other min. values for 5m & 1h resolutions which Thanos currently does not verify for these min. values for the respective Cmd line args.

2022-01-12 23:23 UTC, spaparaju commented
> I think we might just all understand the 'data loss' differently here, if I'm reading the conversations correctly. While this alert does not mean we lost existing data, it is indicating that even though we should be continuously seeing new data being loaded, there was nothing loaded in last 6 hours - this can indicate that there is something wrong with data ingestion and that we are 'losing' this data, since we're not seeing them being loaded and they perhaps are getting 'lost' somewhere on the way to us (e.g. due to misconfiguration).
> 
> Does that make sense @spaparaju @ianbillett?
Yes @matej-g . This alert is on the Store component.  When RHOBS does experience a data loss i.e users not able to see any data (there can be n-possible reasons, one reason resulted in the outage that we experienced is because down-sampled-resolutions are not same and min. values are not currently enforced at the Thanos Compact), the Store component would not be loading any blocks from the Object store (Thanos Store syncs blocks as per `--sync-block-duration`). The metric `thanos_bucket_store_blocks_last_loaded_timestamp_seconds` captures the timestamp whenever sync. can load the blocks and this alert is based on if no block loads happen for the last 6 hours.
> 
> As for similar alerts, we are alerting on compactor not uploading in the last 24 hours and there is also `ThanosReceiveNoUpload`, but I guess we don't have similar alerting from the store side.

2022-01-12 23:23 UTC, spaparaju commented on docs/sop/observatorium.md
> +        - --retention.resolution-1h
When RHOBS does experience a data loss i.e users not able to see any data (there can be n-possible reasons, one reason resulted in the outage that we experienced is because down-sampled-resolutions are not same and min. values are not currently enforced at the Thanos Compact), the Store component would not be loading any blocks from the Object store (Thanos Store syncs blocks as per `--sync-block-duration`). The metric `thanos_bucket_store_blocks_last_loaded_timestamp_seconds` captures the timestamp whenever sync. can load the blocks and this alert is based on if no block loads happen for the last 6 hours.

2022-01-12 23:25 UTC, spaparaju commented on observability/prometheusrules.jsonnet
> +                severity: 'critical',
Changed to `High`.  As per my experience with SRE while adding new alerts, SRE  would have an opinion as well. :)

2022-01-13 09:36 UTC, matej-g commented
Thanks for the explanation @spaparaju :+1:, do we have now common understanding @ianbillett? Do you still feel like this alert is lacking merit?

2022-01-13 11:22 UTC, ianbillett reviewed
There is some value in this alert. However, if we are going to accept this alert, we need to be much clearer about what this alert means, what the potential causes are and what the debugging steps a responder would take. The compactor configuration options is only a small part of this story.

2022-01-13 11:22 UTC, ianbillett commented on docs/sop/observatorium.md
> +        - --retention.resolution-1h needs to be more than 10 days
For us to accept this alert, we need to add more context to the steps outlined here to help the engineer responding to the task. 

* This alert tells us that `Store` has not synced any blocks in the past 6h. This could be due to multiple reasons:
  * Thanos Store is unable to communicate with object store.
  * No new blocks are being uploaded to object store. This indicates that both `Receive` and `Compact` are not uploading new blocks.
* Check on the health of the affected `Store` component.
  * Check the logs - are there any errors?
  * Check the `Store` dashboard - are there any obvious problems?
  * Check the secrets `Store` is using to communicate with Object storage.
 * Validate that both `Receive` and `Compact` are uploading new blocks to Object storage.
   * Investigate Receive
     * Check the `Receive` logs.
     * Check the `Receive` dashboard.
   * Investigate Compactor
     * Check the `Compactor` logs.
     * Check the `Compactor` dashboard.
     * Check the `Compactor` configuration:
       * `<insert the compactor config here>`
    * Investigate Object Storage (you will need AppSRE's help)
      * When was the last time that a block was uploaded?

2022-01-13 11:24 UTC, ianbillett commented on observability/prometheusrules.jsonnet
> +                summary: 'Observatorium Thanos Store has not loaded even a sigle block in the last 6 hours.',
```suggestion
                description: 'Observatorium Thanos Store {{$labels.namespace}}/{{$labels.job}} has not loaded any blocks in the last 6 hours.',
                summary: 'Observatorium Thanos Store has not loaded any blocks in the last 6 hours.',
```

2022-01-18 19:32 UTC, spaparaju commented on resources/observability/prometheusrules/observatorium-thanos-production.prometheusrules.yaml
> -    - alert: ThanosReceiveTrafficBelowThreshold
it was caused by Jsonnet dependency resolution. Fixed this problem, not changing anything related to `ThanosReceiveTrafficBelowThreshold` alert

2022-01-18 19:32 UTC, spaparaju commented on docs/sop/observatorium.md
> +        - --retention.resolution-1h needs to be more than 10 days
Great suggestions. Updated context for this alert.

2022-01-19 13:32 UTC, matej-g approved these changes
Looking good now :+1: I have one more optional suggestion

2022-01-25 09:26 UTC, matej-g commented
@ianbillett satisfied with the state of the alert or are there still any unresolved issues for you?

2022-01-25 10:39 UTC, ianbillett approved these changes
LGTM - Let's merge this puppy :muscle:

2022-01-25 10:53 UTC, merged

2022-01-25 10:54 UTC, matej-g commented
Shall we roll out the alert as well? We will probably need to bump Thanos to the latest (IIRC `v0.24.0`) in our environments cc @spaparaju