Enable stateless Rulers
rhobs/configuration pull request #151
Opened 2022-02-09 15:00 UTC by saswatamcode

This PR 

- Enables stateless Rulers for `observatorium-metrics` and `metric-federation-rule`
- Upgrades `kube-thanos` to latest

Addresses [MON-2128](https://issues.redhat.com/browse/MON-2128).

Note: These changes cannot be rolled out before Thanos v0.25, as support for specifying multiple remote_write targets was added after v0.24 ([thanos#4927](https://github.com/thanos-io/thanos/pull/4927)).

2022-02-10 12:20 UTC, saswatamcode commented on services/observatorium-metrics.libsonnet
> +            url: 'http://observatorium-thanos-receive.%s.svc.cluster.local:19291' % thanosSharedConfig.namespace,
Clarified this with @ianbillett! Need to change it for `metric-federation`,

2022-02-11 12:50 UTC, saswatamcode commented on services/observatorium-metrics.libsonnet
> +            url: 'http://observatorium-thanos-receive.%s.svc.cluster.local:19291' % thanosSharedConfig.namespace,
Done!

2022-03-02 13:52 UTC, matej-g reviewed
Looking good @saswatamcode :+1: My only additional suggestion would be to drop ruler from `--store` in querier args, since it won't be exposing store API anymore, right?

Additionally, as we mention, it would be good to switch ruler from stateful set to deployment, since with stateless mode we have no need to run in stateful set, but this we can do separately later.

2022-03-08 14:23 UTC, ianbillett requested changes
The content of the PR looks good - but we're missing remote write config for all of our other tenants: osd, kafka, dptp etc. 

As every tenant can now create rules, every tenant will need to have an entry in the rw config - the tenant config is available [here](https://vault.devshift.net/ui/vault/secrets/app-interface/show/app-sre-stage/telemeter-stage/observatorium-observatorium-api) & [here](https://vault.devshift.net/ui/vault/secrets/app-interface/show/app-sre-stage/telemeter-stage/observatorium-observatorium-mst-api)

2022-03-09 03:58 UTC, saswatamcode commented
Thanks for catching this @ianbillett! 🙂
I was mistakenly going by the [tenants.libsonnet](https://github.com/rhobs/configuration/blob/main/configuration/observatorium/tenants.libsonnet) file but that wouldn't work here.

2022-03-15 13:12 UTC, ianbillett approved these changes

2022-03-15 13:20 UTC, merged