[rhobs-logs] Upgrade Loki to 2.7.2
rhobs/configuration pull request #396
Opened 2023-01-30 16:53 UTC by aminesnow

Upgrade Loki from 2.6.1 to 2.7.2.

**Depends on:** [observatorium/observatorium/pull/506](https://github.com/observatorium/observatorium/pull/506)

2023-01-31 17:36 UTC, aminesnow commented
CC @periklis

2023-01-31 19:23 UTC, periklis requested changes
Overall looks good to me. Maybe also set the `LOKI_IMAGE_TAG` in `observatorium-logs-template.jsonnet` to `v2.7.2` as to be informative enough for dev-testing that we use 2.7

2023-02-01 09:19 UTC, aminesnow commented on services/observatorium-logs-template.jsonnet
> +    { name: 'LOKI_IMAGE_TAG', value: '2.7.2' },
@periklis this has been already set

2023-02-01 10:10 UTC, periklis commented on services/observatorium-logs-template.jsonnet
> +    { name: 'LOKI_IMAGE_TAG', value: '2.7.2' },
I know I know, but adding this here too improves visibility when you use this repo only, e.g. during creating/testing a PR here without considering observatorium/observatorium

2023-02-01 10:12 UTC, aminesnow commented on services/observatorium-logs-template.jsonnet
> +    { name: 'LOKI_IMAGE_TAG', value: '2.7.2' },
I'm sorry I've no idea what you're talking about here..

2023-02-01 10:14 UTC, periklis approved these changes

2023-02-01 10:16 UTC, aminesnow commented on services/observatorium-logs-template.jsonnet
> +    { name: 'LOKI_IMAGE_TAG', value: '2.7.2' },
Can you please suggest a change so that I understand better

2023-02-01 10:26 UTC, merged