Add separate Querier for Ruler
rhobs/configuration pull request #426
Opened 2023-03-20 05:22 UTC by saswatamcode

Pending ADR.

This PR,

- Removes defunct stateless rulers
- Adds new separate Querier for Rulers to query data from

The architectural changes can be represented as 

Before,
![image](https://user-images.githubusercontent.com/51132453/226253073-c958c017-09f8-4e71-ada5-8ff35bfd1b57.png)

After,
![image](https://user-images.githubusercontent.com/51132453/226253184-4d08e3cb-4a7e-4553-9a35-465ba332ca4c.png)

To deploy,
- Bump metrics template ref and add new OpenShift params
- Bump ServiceMonitor refs
- Bump dashboard ref
- Copy over modified rules

2023-03-21 14:11 UTC, douglascamata requested changes
Just one change suggested.

2023-03-21 14:11 UTC, douglascamata commented on services/observatorium-metrics-template.jsonnet
> +    { name: 'THANOS_RULER_QUERIER_MAX_CONCURRENT', value: '20' },
Can we move all these to the block of configuration variables for Thanos Ruler below? The list of variables seems to be sorted alphabetically and I believe it's great for organization purposes, making it easy to find related configuration.

2023-03-21 14:14 UTC, saswatamcode commented on services/observatorium-metrics-template.jsonnet
> +    { name: 'THANOS_RULER_QUERIER_MAX_CONCURRENT', value: '20' },
Will do!

2023-03-28 13:38 UTC, saswatamcode commented
Yeah fixed in #434 , let me rebase

2023-03-28 14:40 UTC, douglascamata approved these changes
LGTM

2023-04-04 07:36 UTC, saswatamcode commented
Deployment in test cluster looks ok, but there is no data to test. Let's merge and deploy to stage, then iterate.

2023-04-04 07:36 UTC, merged