logs: bump jsonnet dep to start using ConfigMap and Services from loki.mixins
rhobs/configuration pull request #450
Opened 2023-04-06 11:33 UTC by JoaoBraveCoding

See:
- https://github.com/observatorium/observatorium/pull/508
- https://github.com/observatorium/observatorium/pull/511

2023-04-11 07:42 UTC, periklis requested changes
Looks good to me just one entry in the config that should stay as is namely the `index_queries_cache` and a couple of nits.

2023-04-11 07:42 UTC, periklis commented on resources/services/observatorium-logs-template.yaml
> -        "deletion_mode": "disabled"
Although `disabled` is the default, I suggest to keep this here because the Deletion API has caused numerous issues upstream.

2023-04-11 07:42 UTC, periklis commented on resources/services/observatorium-logs-template.yaml
> -            "consistent_hash": true
This should stay here.

2023-04-11 07:42 UTC, periklis commented on services/observatorium-logs-template-overwrites.libsonnet
>                                '-querier.worker-match-max-concurrent',
Please add a TODO here to move this to config var expansion in a follow-up PR.

2023-04-11 07:42 UTC, periklis commented on services/observatorium-logs-template-overwrites.libsonnet
>                                '-ingester.wal-replay-memory-ceiling=${LOKI_INGESTER_WAL_REPLAY_MEMORY_CEILING}',
Please add a TODO here to move this to config var expansion in a follow-up PR.

2023-04-11 10:08 UTC, JoaoBraveCoding commented on resources/services/observatorium-logs-template.yaml
> -        "deletion_mode": "disabled"
Re-added and left a not to move this to observatorium/observatorium since I think it makes more sense to live there

2023-04-11 10:09 UTC, JoaoBraveCoding commented on resources/services/observatorium-logs-template.yaml
> -            "consistent_hash": true
Re-added this, only defaults were removed

2023-04-13 17:36 UTC, JoaoBraveCoding commented
Needs https://github.com/observatorium/observatorium/pull/520

2023-04-16 18:36 UTC, periklis reviewed
LGTM let's ensure we have a clear path to overcome the two rollout issues we found on `rhobs-testing` and this is good to go:
1. How to rollout the `serviceName` change on StatefulSets on app-interface?
2. How to keep the old http service referenced in observatorium-template.yaml in tact to minimize rollout dependencies.

2023-04-17 10:15 UTC, JoaoBraveCoding commented
>     How to rollout the serviceName change on StatefulSets on app-interface?

We should be able to leverage https://github.com/app-sre/qontract-reconcile/pull/1627

>    How to keep the old http service referenced in observatorium-template.yaml intact to minimize rollout dependencies.

To solve this from my POV we would:
1. Include in this PR the old services referenced in `observatorium-template.yaml`
2. Deploy
3. Create a new PR where we update the services in `observatorium-template.yaml`
4. Deploy
5. Create a new PR where we remove the old services
6. Deploy

2023-04-17 10:48 UTC, periklis commented
> > How to rollout the serviceName change on StatefulSets on app-interface?
> 
> We should be able to leverage [app-sre/qontract-reconcile#1627](https://github.com/app-sre/qontract-reconcile/pull/1627)
> 

ACK

> > How to keep the old http service referenced in observatorium-template.yaml intact to minimize rollout dependencies.
> 
> To solve this from my POV we would:
> 
>     1. Include in this PR the old services referenced in `observatorium-template.yaml`
> 
>     2. Deploy
> 
>     3. Create a new PR where we update the services in `observatorium-template.yaml`
> 
>     4. Deploy
> 
>     5. Create a new PR where we remove the old services
> 
>     6. Deploy

ACK

2023-04-17 11:00 UTC, JoaoBraveCoding commented
Once we have https://github.com/observatorium/observatorium/pull/521 merged we will be able to progress on this

2023-04-17 14:28 UTC, merged