initial rhobs utilization dashboard with query front end row
rhobs/configuration pull request #528
Opened 2023-06-22 08:41 UTC by coleenquadros

https://issues.redhat.com/browse/RHOBS-704

2023-06-22 08:45 UTC, coleenquadros commented
staging dashboard - https://grafana.stage.devshift.net/d/G1nb8JX4z/rhobs-instance-utilization-overview?orgId=1&refresh=10s&var-datasource=telemeter-prod-01-prometheus&var-namespace=observatorium-metrics-production&var-interval=5m

Ive given the grid positions for the panels such a way that there are 4 panels per row, but when I copy paste the generated JSON the panels gets stacked on one line.

2023-06-22 09:01 UTC, philipgough commented on observability/dashboards/rhobs-instance-utilization-overview.libsonnet
> +              'kube_pod_container_status_restarts_total{namespace="$namespace", container=\'thanos-query-frontend\'}',
i wonder should we calculate rate for this counter?

2023-06-23 16:57 UTC, douglascamata requested changes
This is missing the link to the query frontend dashboard, no? Do you plan to add it in a follow up PR?

2023-06-23 16:57 UTC, douglascamata commented on observability/dashboards/rhobs-instance-utilization-overview.libsonnet
> +          ) +
For this panel could we simplify things a bit and graph only the working set, for example? There's a good metric for this: `container_memory_working_set_bytes`.

We very rarely look at any Go specific memory metric and when we do mostly we care about in-use heap. So they can stay in the specific dashboard. 👍

2023-06-23 16:57 UTC, douglascamata commented on observability/dashboards/rhobs-instance-utilization-overview.libsonnet
> +  local queryFrontendOpSelector = utils.joinLabels([thanos.queryFrontend.dashboard.selector, 'op="query_range"']),
What about instant queries that the query frontend might handle? 🤔

2023-06-26 08:25 UTC, coleenquadros commented on observability/dashboards/rhobs-instance-utilization-overview.libsonnet
> +          ) +
I picked this up from the mixin itself. So if one were to move to the original component dashboard then this panel will end up being different.

2023-06-26 08:49 UTC, douglascamata commented on observability/dashboards/rhobs-instance-utilization-overview.libsonnet
> +          ) +
Yes, it will be different there. But was there, with all these metrics, is not useful. The chart looks too crowded. Also this chart has only these metrics in Thanos because there it was decided to only use metrics exported from Thanos itself. As `container_memory_working_set_bytes` comes from a different place, it wasn't included.

2023-06-26 09:59 UTC, coleenquadros commented on observability/dashboards/rhobs-instance-utilization-overview.libsonnet
> +  local queryFrontendOpSelector = utils.joinLabels([thanos.queryFrontend.dashboard.selector, 'op="query_range"']),
Removed the `query_range` filter.. Will need to update upstream mixin

2023-06-26 10:20 UTC, douglascamata requested changes
I imported the changed dashboard into our staging environment and noticed a problem with the memory used widget. 

The layout also looks off. Seems like charts are crammed into a very small space. Can you please give them more space so that they look better? It's okay to have more than 1 row/line of widgets.

2023-06-26 10:20 UTC, douglascamata commented on observability/dashboards/rhobs-instance-utilization-overview.libsonnet
> +              '(container_memory_working_set_bytes{container="observatorium-thanos-query-frontend", namespace="$namespace"}[$interval]) / (1024 * 1024)',
This is not a range vector, so the `[$interval]` part won't work and can be safely removed.

2023-06-26 10:56 UTC, coleenquadros commented
> I imported the changed dashboard into our staging environment and noticed a problem with the memory used widget.
> 
> The layout also looks off. Seems like charts are crammed into a very small space. Can you please give them more space so that they look better? It's okay to have more than 1 row/line of widgets.

Thats where I provided the grid positions in the panels to allow the panels to be split as 4 panels in one line. But when I copy the JSON it gets moved to one line

2023-06-26 13:05 UTC, douglascamata requested changes
One final set of changes and I think we can merge this. It's looking pretty good! :D

2023-06-26 13:05 UTC, douglascamata commented on observability/dashboards/rhobs-instance-utilization-overview.libsonnet
> +              'pod {{instance}}',
It doesn't seem like this metric has an `instance` label. We have to use the `pod` label here, I believe. The same applies to the cpu metric just above.

Note that this is already done in the memory metric.

2023-06-26 13:30 UTC, douglascamata commented on observability/dashboards/rhobs-instance-utilization-overview.libsonnet
> +        g.row('Query Frontend Overview')
We are missing the network throughput charts here, as mentioned in the JIRA ticket.

2023-06-26 13:31 UTC, douglascamata commented on observability/dashboards/rhobs-instance-utilization-overview.libsonnet
> +        )
Aren't these two the same thing?

2023-06-26 14:08 UTC, coleenquadros commented on observability/dashboards/rhobs-instance-utilization-overview.libsonnet
> +        )
Yes, they are but represented different in the panels, with one panel using the handler="query-frontend" and the other panel using "op=query_range". We can choose to keep one 

This is taken from the existing thanos query front end dashboard - https://grafana.stage.devshift.net/d/7c68ed2ef2355474f058dd27f0471f7a/thanos-query-frontend?orgId=1&refresh=10s

2023-06-26 15:34 UTC, douglascamata commented on observability/dashboards/rhobs-instance-utilization-overview.libsonnet
> +        )
Let's pick one then. If upstream there wasn't the op filter, these charts would mostly match 100%.

2023-06-27 09:22 UTC, douglascamata approved these changes
Nice one, LGTM :shipit:

2023-06-27 10:00 UTC, merged