Alert for query failures generated by Observatorium proactive monitoring
rhobs/configuration pull request #57
Opened 2021-09-23 19:04 UTC by spaparaju

This PR adds an alert (on stage cluster) if queries generated by proactive monitoring (Observatorium UP) are failing.

2021-09-28 07:33 UTC, matej-g reviewed
Nice going :muscle: I'm glad to see we are getting more and more useful alerts in! I have just few suggestions, otherwise I'll be happy to see this merged.

2021-09-28 07:33 UTC, matej-g commented on docs/sop/observatorium.md
> +- Access to Vault secret for `tenants.yaml` (link for [staging](https://vault.devshift.net/ui/vault/secrets/app-interface/show/app-sre-stage/telemeter-stage/observatorium-observatorium-api); for [pro
Is there a reason we need tenants config? The steps below instruct to just check the logs.

2021-09-28 07:33 UTC, matej-g commented on docs/sop/observatorium.md
> +Metrics queries generated by Proactive monitoring are failing.
Here maybe I would switch `Impact` and `Summary` content, as this sounds more like summary of the issue.

2021-09-28 07:33 UTC, matej-g commented on observability/prometheusrules.jsonnet
> +                ( sum by (namespace, job) (rate(up_custom_query_errors_total[5m])) / sum by (namespace, job) (rate(up_custom_query_executed_total[5m]))) * 100 > 25
Is there any reason to choose value `25` here over something smaller?

2021-09-28 11:09 UTC, ianbillett requested changes
Looking pretty nice! The only blocking question I would ask is - should we wait to ship this alert until we've merged https://github.com/observatorium/up/pull/35? That way the alert can contain much more useful information for the recipient. WDYT @spaparaju ?

2021-09-28 16:04 UTC, spaparaju commented on docs/sop/observatorium.md
> +- Access to Vault secret for `tenants.yaml` (link for [staging](https://vault.devshift.net/ui/vault/secrets/app-interface/show/app-sre-stage/telemeter-stage/observatorium-observatorium-api); for [pro
misconfigured tenants at 'tenants.yaml' can cause queries to fail. Would require access to Vault secrets for debugging for this kinda scenario.

2021-09-28 16:04 UTC, spaparaju commented on docs/sop/observatorium.md
> +Metrics queries generated by Proactive monitoring are failing.
👍

2021-09-28 16:07 UTC, spaparaju commented on observability/prometheusrules.jsonnet
> +                severity: 'warning',
manifest [generation](https://github.com/rhobs/configuration/blob/b018097acccb5f4b667c70fe47b5ee27c48785f8/observability/prometheusrules.jsonnet#L101) turn 'warining' into 'medium' severity.

2021-09-28 16:08 UTC, spaparaju commented on docs/sop/observatorium.md
> +- Check the logs of Observatorium API deployment's [pods](https://console-openshift-console.apps.telemeter-prod.a5j2.p1.openshiftapps.com/k8s/ns/telemeter-production/deployments/observatorium-observa
👍 In addition to this, included logs of Obs-API pods for both telemeter, MST tenants.

2021-09-28 16:10 UTC, spaparaju commented
> Looking pretty nice! The only blocking question I would ask is - should we wait to ship this alert until we've merged [observatorium/up#35](https://github.com/observatorium/up/pull/35)? That way the alert can contain much more useful information for the recipient. WDYT @spaparaju ?

To merge this PR, I do not see any hard dependency on [PR](https://github.com/observatorium/up/pull/35) to include HTTP response codes.

2021-09-28 16:29 UTC, matej-g commented on docs/sop/observatorium.md
> +- Access to Vault secret for `tenants.yaml` (link for [staging](https://vault.devshift.net/ui/vault/secrets/app-interface/show/app-sre-stage/telemeter-stage/observatorium-observatorium-api); for [pro
Can we just mention this briefly in the steps to recover?  I.e. where to find the secret, what needs to be checked etc.

2021-09-29 08:33 UTC, matej-g commented
> To merge this PR, I do not see any hard dependency on [PR](https://github.com/observatorium/up/pull/35) to include HTTP response codes.

Agreed with @spaparaju, this should be good enough to start with, once we have the HTTP codes in and we want to distinguish between errors (e.g. server errors vs. request errors) we can do that additionally.

2021-10-05 01:06 UTC, spaparaju commented on docs/sop/observatorium.md
> +- Access to Vault secret for `tenants.yaml` (link for [staging](https://vault.devshift.net/ui/vault/secrets/app-interface/show/app-sre-stage/telemeter-stage/observatorium-observatorium-api); for [pro
add a new step for what to check inside tenants.yaml

2021-10-05 06:58 UTC, matej-g reviewed
I have just one last unaddressed point about the threshold for the alert, otherwise happy to approve :+1:

2021-10-05 06:58 UTC, matej-g commented on docs/sop/observatorium.md
> +- Check the Vault secret for `tenants.yaml` (link for [staging](https://vault.devshift.net/ui/vault/secrets/app-interface/show/app-sre-stage/telemeter-stage/observatorium-observatorium-api); for [pro
```suggestion
- Check the Vault secret for `tenants.yaml` (link for [staging](https://vault.devshift.net/ui/vault/secrets/app-interface/show/app-sre-stage/telemeter-stage/observatorium-observatorium-api); for [production](https://vault.devshift.net/ui/vault/secrets/app-interface/show/app-sre/telemeter-production/observatorium-observatorium-api) for valid YAML content, valid tenant name, auth information under 'oidc' and 'opa' sections and rate limting information under 'rateLimits' section.
```

Maybe I would just mention for production, we have to contact AppSRE since we do not have access ourselves.

2021-10-05 06:58 UTC, matej-g commented on resources/observability/prometheusrules/observatorium-proactive-monitoring-production.prometheusrules.yaml
> +        ( sum by (namespace, job, query) (rate(up_custom_query_errors_total[5m])) / sum by (namespace, job, query) (rate(up_custom_query_executed_total[5m]))) * 100 > 25
Has this https://github.com/rhobs/configuration/pull/57#discussion_r717302593 been addressed?

2021-10-05 13:02 UTC, spaparaju commented on observability/prometheusrules.jsonnet
> +                ( sum by (namespace, job) (rate(up_custom_query_errors_total[5m])) / sum by (namespace, job) (rate(up_custom_query_executed_total[5m]))) * 100 > 25
25% is a rough signal that significant # of queries failing. why not 50% or 10% ? Just a balance between 'too noisy' and 'too late' kinda scenarios.

2021-10-05 14:19 UTC, ianbillett approved these changes
LGTM % @matej-g 's outstanding questions

2021-10-06 09:08 UTC, matej-g approved these changes

2021-10-06 09:11 UTC, merged