WIP: Add receive go config
rhobs/configuration pull request #620
Opened 2023-10-09 15:23 UTC by thibaultmg

2023-10-18 12:11 UTC, philipgough commented on resources/services/app-sre-stage-01/rhobs/default/observatorium-metrics-receive-router-default-template.yaml
> +          - '----namespace=rhobs'
are these flags correct? maybe should be `--`

2023-10-18 12:12 UTC, philipgough commented on resources/services/app-sre-stage-01/rhobs/default/observatorium-metrics-receive-router-default-template.yaml
> +          - --log.level=${THANOS_LOG_LEVEL}
a nit but since we split by templates can we just drop the THANOS_ prefix from this param?

2023-10-18 12:15 UTC, philipgough requested changes
I believe the intention was that we would share the routing layer for receivers and have ingestors per tenant

2023-10-18 12:16 UTC, philipgough commented on resources/services/app-sre-stage-01/rhobs/default/observatorium-metrics-receive-ingestor-default-template.yaml
> +- apiVersion: apps/v1
We will need a PodDisruptionBudget for this!

2023-10-18 12:17 UTC, philipgough commented on resources/services/app-sre-stage-01/rhobs/default/observatorium-metrics-receive-router-default-template.yaml
> +  kind: Deployment
We will need a PodDisruptionBudget for this!

2023-10-18 12:18 UTC, philipgough commented on resources/services/app-sre-stage-01/rhobs/rhel/observatorium-metrics-receive-router-rhel-template.yaml
> +  kind: Deployment
We will need a PodDisruptionBudget for this!

2023-10-18 12:19 UTC, philipgough commented on resources/services/app-sre-stage-01/rhobs/rhel/observatorium-metrics-receive-router-rhel-template.yaml
> +  kind: Deployment
We will need a PodDisruptionBudget for this!

2023-10-24 07:59 UTC, thibaultmg commented on resources/services/app-sre-stage-01/rhobs/default/observatorium-metrics-receive-router-default-template.yaml
> +          - '----namespace=rhobs'
fixed

2023-10-24 08:00 UTC, thibaultmg commented on resources/services/app-sre-stage-01/rhobs/default/observatorium-metrics-receive-router-default-template.yaml
> +          - --log.level=${THANOS_LOG_LEVEL}
I did that to distinguish it from the sidecars. But since we are not using more parameters, and we want to avoid that, makes sense.
Updated

2023-10-24 08:00 UTC, thibaultmg commented on resources/services/app-sre-stage-01/rhobs/default/observatorium-metrics-receive-ingestor-default-template.yaml
> +- apiVersion: apps/v1
done

2023-10-24 08:01 UTC, thibaultmg commented
> I believe the intention was that we would share the routing layer for receivers and have ingestors per tenant

Ok, I have updated the generation to do that. Let me know if that works for you.

2023-10-24 09:20 UTC, philipgough approved these changes
lgtm

2023-10-24 09:23 UTC, merged